"""Añade campos de estimación a Analisis

Revision ID: 12657b39b5ff
Revises: c99043f290be
Create Date: 2025-11-13 22:57:05.436960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12657b39b5ff'
down_revision = 'c99043f290be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horas_diseño_estimadas', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('horas_ejecucion_estimadas', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis', schema=None) as batch_op:
        batch_op.drop_column('horas_ejecucion_estimadas')
        batch_op.drop_column('horas_diseño_estimadas')

    # ### end Alembic commands ###
