"""Añade HistorialCambios y is_active

Revision ID: 58c6686e9796
Revises: 
Create Date: 2025-11-15 22:09:37.651867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c6686e9796'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_cambios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_analisis', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tipo_cambio', sa.String(length=50), nullable=True),
    sa.Column('datos_json_antiguos', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_analisis'], ['analisis.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historial_cambios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_cambios_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('analisis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_analisis_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('analisis_dato', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_analisis_dato_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis_dato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analisis_dato_timestamp'))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('analisis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analisis_is_active'))
        batch_op.drop_column('is_active')

    with op.batch_alter_table('historial_cambios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_cambios_timestamp'))

    op.drop_table('historial_cambios')
    # ### end Alembic commands ###
