"""Añade tabla Analisis para historial

Revision ID: 64e7f783b780
Revises: bdd92b2ba39f
Create Date: 2025-11-11 20:26:00.056969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e7f783b780'
down_revision = 'bdd92b2ba39f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analisis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_plantilla', sa.Integer(), nullable=True),
    sa.Column('nombre_requerimiento', sa.String(length=255), nullable=True),
    sa.Column('texto_requerimiento_raw', sa.Text(), nullable=True),
    sa.Column('nivel_complejidad', sa.String(length=100), nullable=True),
    sa.Column('casos_generados', sa.Integer(), nullable=True),
    sa.Column('criterios_detectados', sa.Integer(), nullable=True),
    sa.Column('palabras_analizadas', sa.Integer(), nullable=True),
    sa.Column('ai_result_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_plantilla'], ['plantilla.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analisis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analisis_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analisis_timestamp'))

    op.drop_table('analisis')
    # ### end Alembic commands ###
