"""Añade sheet_name y header_row a Plantilla

Revision ID: bdd92b2ba39f
Revises: cce774ff580f
Create Date: 2025-11-10 19:39:44.607087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd92b2ba39f'
down_revision = 'cce774ff580f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sheet_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('header_row', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla', schema=None) as batch_op:
        batch_op.drop_column('header_row')
        batch_op.drop_column('sheet_name')

    # ### end Alembic commands ###
