"""Añade contador de criterios no funcionales

Revision ID: c99043f290be
Revises: e16a1aaf9517
Create Date: 2025-11-13 22:49:23.639310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99043f290be'
down_revision = 'e16a1aaf9517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criterios_no_funcionales', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analisis', schema=None) as batch_op:
        batch_op.drop_column('criterios_no_funcionales')

    # ### end Alembic commands ###
