"""Creación inicial de tablas (versión limpia)

Revision ID: cce774ff580f
Revises: 
Create Date: 2025-11-01 23:26:41.998905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce774ff580f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('plantilla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_plantilla', sa.String(length=140), nullable=True),
    sa.Column('tipo_archivo', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('filename_seguro', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plantilla', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plantilla_timestamp'), ['timestamp'], unique=False)

    op.create_table('mapa_plantilla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etiqueta', sa.String(length=140), nullable=True),
    sa.Column('coordenada', sa.String(length=140), nullable=True),
    sa.Column('tipo_mapa', sa.String(length=50), nullable=True),
    sa.Column('id_plantilla', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_plantilla'], ['plantilla.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mapa_plantilla', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mapa_plantilla_etiqueta'), ['etiqueta'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapa_plantilla', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mapa_plantilla_etiqueta'))

    op.drop_table('mapa_plantilla')
    with op.batch_alter_table('plantilla', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plantilla_timestamp'))

    op.drop_table('plantilla')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    # ### end Alembic commands ###
