"""Añade desglosar_pasos a Plantilla

Revision ID: e16a1aaf9517
Revises: 64e7f783b780
Create Date: 2025-11-13 20:15:42.658405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16a1aaf9517'
down_revision = '64e7f783b780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desglosar_pasos', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla', schema=None) as batch_op:
        batch_op.drop_column('desglosar_pasos')

    # ### end Alembic commands ###
